
// Generated by FABulous
// Top wrapper for user design user_design/regfile_test_20.v

module top_wrapper #(
    parameter NUM_REGFILES = 20  // Number of RegFiles (1-20)
);

wire clk;
(* keep *) Global_Clock clk_i (.CLK(clk));

(* keep, BEL="X2Y0.A" *) N_IO_GenIO bel_X2Y0_A (.NIO_I(N_IO_GenIO_NIO_I[0]), .NIO_O(N_IO_GenIO_NIO_O[0]));
(* keep, BEL="X3Y0.A" *) N_IO_GenIO bel_X3Y0_A (.NIO_I(N_IO_GenIO_NIO_I[1]), .NIO_O(N_IO_GenIO_NIO_O[1]));
(* keep, BEL="X4Y0.A" *) N_IO_GenIO bel_X4Y0_A (.NIO_I(N_IO_GenIO_NIO_I[2]), .NIO_O(N_IO_GenIO_NIO_O[2]));
(* keep, BEL="X5Y0.A" *) N_IO_GenIO bel_X5Y0_A (.NIO_I(N_IO_GenIO_NIO_I[3]), .NIO_O(N_IO_GenIO_NIO_O[3]));
(* keep, BEL="X6Y0.A" *) N_IO_GenIO bel_X6Y0_A (.NIO_I(N_IO_GenIO_NIO_I[4]), .NIO_O(N_IO_GenIO_NIO_O[4]));
(* keep, BEL="X7Y0.A" *) N_IO_GenIO bel_X7Y0_A (.NIO_I(N_IO_GenIO_NIO_I[5]), .NIO_O(N_IO_GenIO_NIO_O[5]));
(* keep, BEL="X8Y0.A" *) N_IO_GenIO bel_X8Y0_A (.NIO_I(N_IO_GenIO_NIO_I[6]), .NIO_O(N_IO_GenIO_NIO_O[6]));
(* keep, BEL="X9Y0.A" *) N_IO_GenIO bel_X9Y0_A (.NIO_I(N_IO_GenIO_NIO_I[7]), .NIO_O(N_IO_GenIO_NIO_O[7]));
(* keep, BEL="X10Y0.A" *) N_IO_GenIO bel_X10Y0_A (.NIO_I(N_IO_GenIO_NIO_I[8]), .NIO_O(N_IO_GenIO_NIO_O[8]));
(* keep, BEL="X11Y0.A" *) N_IO_GenIO bel_X11Y0_A (.NIO_I(N_IO_GenIO_NIO_I[9]), .NIO_O(N_IO_GenIO_NIO_O[9]));
(* keep, BEL="X12Y0.A" *) N_IO_GenIO bel_X12Y0_A (.NIO_I(N_IO_GenIO_NIO_I[10]), .NIO_O(N_IO_GenIO_NIO_O[10]));
(* keep, BEL="X13Y0.A" *) N_IO_GenIO bel_X13Y0_A (.NIO_I(N_IO_GenIO_NIO_I[11]), .NIO_O(N_IO_GenIO_NIO_O[11]));
(* keep, BEL="X14Y0.A" *) N_IO_GenIO bel_X14Y0_A (.NIO_I(N_IO_GenIO_NIO_I[12]), .NIO_O(N_IO_GenIO_NIO_O[12]));
(* keep, BEL="X15Y0.A" *) N_IO_GenIO bel_X15Y0_A (.NIO_I(N_IO_GenIO_NIO_I[13]), .NIO_O(N_IO_GenIO_NIO_O[13]));
(* keep, BEL="X16Y0.A" *) N_IO_GenIO bel_X16Y0_A (.NIO_I(N_IO_GenIO_NIO_I[14]), .NIO_O(N_IO_GenIO_NIO_O[14]));
(* keep, BEL="X17Y0.A" *) N_IO_GenIO bel_X17Y0_A (.NIO_I(N_IO_GenIO_NIO_I[15]), .NIO_O(N_IO_GenIO_NIO_O[15]));
(* keep, BEL="X18Y0.A" *) N_IO_GenIO bel_X18Y0_A (.NIO_I(N_IO_GenIO_NIO_I[16]), .NIO_O(N_IO_GenIO_NIO_O[16]));
(* keep, BEL="X19Y0.A" *) N_IO_GenIO bel_X19Y0_A (.NIO_I(N_IO_GenIO_NIO_I[17]), .NIO_O(N_IO_GenIO_NIO_O[17]));
(* keep, BEL="X20Y0.A" *) N_IO_GenIO bel_X20Y0_A (.NIO_I(N_IO_GenIO_NIO_I[18]), .NIO_O(N_IO_GenIO_NIO_O[18]));
(* keep, BEL="X21Y0.A" *) N_IO_GenIO bel_X21Y0_A (.NIO_I(N_IO_GenIO_NIO_I[19]), .NIO_O(N_IO_GenIO_NIO_O[19]));
(* keep, BEL="X22Y0.A" *) N_IO_GenIO bel_X22Y0_A (.NIO_I(N_IO_GenIO_NIO_I[20]), .NIO_O(N_IO_GenIO_NIO_O[20]));
(* keep, BEL="X23Y0.A" *) N_IO_GenIO bel_X23Y0_A (.NIO_I(N_IO_GenIO_NIO_I[21]), .NIO_O(N_IO_GenIO_NIO_O[21]));
(* keep, BEL="X24Y0.A" *) N_IO_GenIO bel_X24Y0_A (.NIO_I(N_IO_GenIO_NIO_I[22]), .NIO_O(N_IO_GenIO_NIO_O[22]));
(* keep, BEL="X25Y0.A" *) N_IO_GenIO bel_X25Y0_A (.NIO_I(N_IO_GenIO_NIO_I[23]), .NIO_O(N_IO_GenIO_NIO_O[23]));
(* keep, BEL="X26Y0.A" *) N_IO_GenIO bel_X26Y0_A (.NIO_I(N_IO_GenIO_NIO_I[24]), .NIO_O(N_IO_GenIO_NIO_O[24]));
(* keep, BEL="X27Y0.A" *) N_IO_GenIO bel_X27Y0_A (.NIO_I(N_IO_GenIO_NIO_I[25]), .NIO_O(N_IO_GenIO_NIO_O[25]));
(* keep, BEL="X28Y0.A" *) N_IO_GenIO bel_X28Y0_A (.NIO_I(N_IO_GenIO_NIO_I[26]), .NIO_O(N_IO_GenIO_NIO_O[26]));
(* keep, BEL="X29Y0.A" *) N_IO_GenIO bel_X29Y0_A (.NIO_I(N_IO_GenIO_NIO_I[27]), .NIO_O(N_IO_GenIO_NIO_O[27]));


// bel N_IO_GenIO input wires:
wire [27:0]N_IO_GenIO_NIO_I;
// bel N_IO_GenIO output wires:
wire [27:0]N_IO_GenIO_NIO_O;


// instantiate user_design
regfile_test_20 #(
    .NUM_REGFILES(NUM_REGFILES)
) user_design_i (
    .clk(clk),
    .io_in(N_IO_GenIO_NIO_O),
    .io_out(N_IO_GenIO_NIO_I)
);

endmodule //top_wrapper
