
// Generated by FABulous
// Top wrapper for user design user_design/sequential_16bit_en.v

module top_wrapper;

wire clk;
(* keep *) Global_Clock clk_i (.CLK(clk));

//(* keep, BEL="X0Y8.D" *) Config_access bel_X0Y8_D ();
//(* keep, BEL="X0Y8.C" *) Config_access bel_X0Y8_C ();
(* keep, BEL="X0Y8.B" *) IO_1_bidirectional_frame_config_pass bel_X0Y8_B (.I(IO_1_bidirectional_frame_config_pass_I[0]), .T(IO_1_bidirectional_frame_config_pass_T[0]), .O(IO_1_bidirectional_frame_config_pass_O[0]), .Q(IO_1_bidirectional_frame_config_pass_Q[0]));
(* keep, BEL="X0Y8.A" *) IO_1_bidirectional_frame_config_pass bel_X0Y8_A (.I(IO_1_bidirectional_frame_config_pass_I[1]), .T(IO_1_bidirectional_frame_config_pass_T[1]), .O(IO_1_bidirectional_frame_config_pass_O[1]), .Q(IO_1_bidirectional_frame_config_pass_Q[1]));
//(* keep, BEL="X0Y7.D" *) Config_access bel_X0Y7_D ();
//(* keep, BEL="X0Y7.C" *) Config_access bel_X0Y7_C ();
(* keep, BEL="X0Y7.B" *) IO_1_bidirectional_frame_config_pass bel_X0Y7_B (.I(IO_1_bidirectional_frame_config_pass_I[2]), .T(IO_1_bidirectional_frame_config_pass_T[2]), .O(IO_1_bidirectional_frame_config_pass_O[2]), .Q(IO_1_bidirectional_frame_config_pass_Q[2]));
(* keep, BEL="X0Y7.A" *) IO_1_bidirectional_frame_config_pass bel_X0Y7_A (.I(IO_1_bidirectional_frame_config_pass_I[3]), .T(IO_1_bidirectional_frame_config_pass_T[3]), .O(IO_1_bidirectional_frame_config_pass_O[3]), .Q(IO_1_bidirectional_frame_config_pass_Q[3]));
//(* keep, BEL="X0Y6.D" *) Config_access bel_X0Y6_D ();
//(* keep, BEL="X0Y6.C" *) Config_access bel_X0Y6_C ();
(* keep, BEL="X0Y6.B" *) IO_1_bidirectional_frame_config_pass bel_X0Y6_B (.I(IO_1_bidirectional_frame_config_pass_I[4]), .T(IO_1_bidirectional_frame_config_pass_T[4]), .O(IO_1_bidirectional_frame_config_pass_O[4]), .Q(IO_1_bidirectional_frame_config_pass_Q[4]));
(* keep, BEL="X0Y6.A" *) IO_1_bidirectional_frame_config_pass bel_X0Y6_A (.I(IO_1_bidirectional_frame_config_pass_I[5]), .T(IO_1_bidirectional_frame_config_pass_T[5]), .O(IO_1_bidirectional_frame_config_pass_O[5]), .Q(IO_1_bidirectional_frame_config_pass_Q[5]));
//(* keep, BEL="X0Y5.D" *) Config_access bel_X0Y5_D ();
//(* keep, BEL="X0Y5.C" *) Config_access bel_X0Y5_C ();
(* keep, BEL="X0Y5.B" *) IO_1_bidirectional_frame_config_pass bel_X0Y5_B (.I(IO_1_bidirectional_frame_config_pass_I[6]), .T(IO_1_bidirectional_frame_config_pass_T[6]), .O(IO_1_bidirectional_frame_config_pass_O[6]), .Q(IO_1_bidirectional_frame_config_pass_Q[6]));
(* keep, BEL="X0Y5.A" *) IO_1_bidirectional_frame_config_pass bel_X0Y5_A (.I(IO_1_bidirectional_frame_config_pass_I[7]), .T(IO_1_bidirectional_frame_config_pass_T[7]), .O(IO_1_bidirectional_frame_config_pass_O[7]), .Q(IO_1_bidirectional_frame_config_pass_Q[7]));
//(* keep, BEL="X0Y4.D" *) Config_access bel_X0Y4_D ();
//(* keep, BEL="X0Y4.C" *) Config_access bel_X0Y4_C ();
(* keep, BEL="X0Y4.B" *) IO_1_bidirectional_frame_config_pass bel_X0Y4_B (.I(IO_1_bidirectional_frame_config_pass_I[8]), .T(IO_1_bidirectional_frame_config_pass_T[8]), .O(IO_1_bidirectional_frame_config_pass_O[8]), .Q(IO_1_bidirectional_frame_config_pass_Q[8]));
(* keep, BEL="X0Y4.A" *) IO_1_bidirectional_frame_config_pass bel_X0Y4_A (.I(IO_1_bidirectional_frame_config_pass_I[9]), .T(IO_1_bidirectional_frame_config_pass_T[9]), .O(IO_1_bidirectional_frame_config_pass_O[9]), .Q(IO_1_bidirectional_frame_config_pass_Q[9]));
//(* keep, BEL="X0Y3.D" *) Config_access bel_X0Y3_D ();
//(* keep, BEL="X0Y3.C" *) Config_access bel_X0Y3_C ();
(* keep, BEL="X0Y3.B" *) IO_1_bidirectional_frame_config_pass bel_X0Y3_B (.I(IO_1_bidirectional_frame_config_pass_I[10]), .T(IO_1_bidirectional_frame_config_pass_T[10]), .O(IO_1_bidirectional_frame_config_pass_O[10]), .Q(IO_1_bidirectional_frame_config_pass_Q[10]));
(* keep, BEL="X0Y3.A" *) IO_1_bidirectional_frame_config_pass bel_X0Y3_A (.I(IO_1_bidirectional_frame_config_pass_I[11]), .T(IO_1_bidirectional_frame_config_pass_T[11]), .O(IO_1_bidirectional_frame_config_pass_O[11]), .Q(IO_1_bidirectional_frame_config_pass_Q[11]));
//(* keep, BEL="X0Y2.D" *) Config_access bel_X0Y2_D ();
//(* keep, BEL="X0Y2.C" *) Config_access bel_X0Y2_C ();
(* keep, BEL="X0Y2.B" *) IO_1_bidirectional_frame_config_pass bel_X0Y2_B (.I(IO_1_bidirectional_frame_config_pass_I[12]), .T(IO_1_bidirectional_frame_config_pass_T[12]), .O(IO_1_bidirectional_frame_config_pass_O[12]), .Q(IO_1_bidirectional_frame_config_pass_Q[12]));
(* keep, BEL="X0Y2.A" *) IO_1_bidirectional_frame_config_pass bel_X0Y2_A (.I(IO_1_bidirectional_frame_config_pass_I[13]), .T(IO_1_bidirectional_frame_config_pass_T[13]), .O(IO_1_bidirectional_frame_config_pass_O[13]), .Q(IO_1_bidirectional_frame_config_pass_Q[13]));
//(* keep, BEL="X0Y1.D" *) Config_access bel_X0Y1_D ();
//(* keep, BEL="X0Y1.C" *) Config_access bel_X0Y1_C ();
(* keep, BEL="X0Y1.B" *) IO_1_bidirectional_frame_config_pass bel_X0Y1_B (.I(IO_1_bidirectional_frame_config_pass_I[14]), .T(IO_1_bidirectional_frame_config_pass_T[14]), .O(IO_1_bidirectional_frame_config_pass_O[14]), .Q(IO_1_bidirectional_frame_config_pass_Q[14]));
(* keep, BEL="X0Y1.A" *) IO_1_bidirectional_frame_config_pass bel_X0Y1_A (.I(IO_1_bidirectional_frame_config_pass_I[15]), .T(IO_1_bidirectional_frame_config_pass_T[15]), .O(IO_1_bidirectional_frame_config_pass_O[15]), .Q(IO_1_bidirectional_frame_config_pass_Q[15]));


// bel IO_1_bidirectional_frame_config_pass input wires:
wire [15:0]IO_1_bidirectional_frame_config_pass_I;
wire [15:0]IO_1_bidirectional_frame_config_pass_T;
// bel IO_1_bidirectional_frame_config_pass output wires:
wire [15:0]IO_1_bidirectional_frame_config_pass_O;
wire [15:0]IO_1_bidirectional_frame_config_pass_Q;


// instantiate user_design
sequential_16bit_en user_design_i (.clk(clk), .io_in(IO_1_bidirectional_frame_config_pass_O), .io_out(IO_1_bidirectional_frame_config_pass_I), .io_oeb(IO_1_bidirectional_frame_config_pass_T));


endmodule //top_wrapper
